version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  backend-blog:
    build: ./backend-blog
    ports:
      - "8001:8000"
    volumes:
      - ./backend-blog:/app
    restart: always

  backend-user:
    build: ./backend-user
    ports:
      - "8002:8000"
    volumes:
      - ./backend-user:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always

  # CMS service commented out as frontend-blog directory doesn't exist
  # Uncomment and update the path when the frontend-blog directory is created
  # cms:
  #   build: ./frontend-blog
  #   ports:
  #     - "3001:5173"
  #   volumes:
  #     - ./frontend-blog:/app
  #   restart: always

  transcoder:
    build: ./transcoder
    ports:
      - "8080:8080"
    volumes:
      - ./transcoder/upload:/app/upload
      - ./transcoder/output:/app/output
    restart: always
